//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryConverterClient.BinaryConverterServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Lab4ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost", ConfigurationName="BinaryConverterServiceReference.IBinaryConverter")]
    public interface IBinaryConverter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IBinaryConverter/GetBinary", ReplyAction="http://localhost/IBinaryConverter/GetBinaryResponse")]
        string GetBinary(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IBinaryConverter/GetBinary", ReplyAction="http://localhost/IBinaryConverter/GetBinaryResponse")]
        System.Threading.Tasks.Task<string> GetBinaryAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IBinaryConverter/GetOneCount", ReplyAction="http://localhost/IBinaryConverter/GetOneCountResponse")]
        string GetOneCount(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IBinaryConverter/GetOneCount", ReplyAction="http://localhost/IBinaryConverter/GetOneCountResponse")]
        System.Threading.Tasks.Task<string> GetOneCountAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IBinaryConverter/GetDataUsingDataContract", ReplyAction="http://localhost/IBinaryConverter/GetDataUsingDataContractResponse")]
        BinaryConverterClient.BinaryConverterServiceReference.CompositeType GetDataUsingDataContract(BinaryConverterClient.BinaryConverterServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IBinaryConverter/GetDataUsingDataContract", ReplyAction="http://localhost/IBinaryConverter/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BinaryConverterClient.BinaryConverterServiceReference.CompositeType> GetDataUsingDataContractAsync(BinaryConverterClient.BinaryConverterServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBinaryConverterChannel : BinaryConverterClient.BinaryConverterServiceReference.IBinaryConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BinaryConverterClient : System.ServiceModel.ClientBase<BinaryConverterClient.BinaryConverterServiceReference.IBinaryConverter>, BinaryConverterClient.BinaryConverterServiceReference.IBinaryConverter {
        
        public BinaryConverterClient() {
        }
        
        public BinaryConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BinaryConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BinaryConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BinaryConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBinary(int value) {
            return base.Channel.GetBinary(value);
        }
        
        public System.Threading.Tasks.Task<string> GetBinaryAsync(int value) {
            return base.Channel.GetBinaryAsync(value);
        }
        
        public string GetOneCount(int value) {
            return base.Channel.GetOneCount(value);
        }
        
        public System.Threading.Tasks.Task<string> GetOneCountAsync(int value) {
            return base.Channel.GetOneCountAsync(value);
        }
        
        public BinaryConverterClient.BinaryConverterServiceReference.CompositeType GetDataUsingDataContract(BinaryConverterClient.BinaryConverterServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BinaryConverterClient.BinaryConverterServiceReference.CompositeType> GetDataUsingDataContractAsync(BinaryConverterClient.BinaryConverterServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
